#!/bin/bash

version="0.2.1"

cat > ./Sources/XcodeSimulatorKit/Version.swift <<EOF
// 
// This file is generated by generate-version-swift.sh.
//

public extension XcodeSimulatorCert {
    static var version: String {
        return "${version}"
    }
}
