// 
// NOTE: This file is automatically generated by generate-version-swift.sh.
// Should not be under version control.
//

public extension XcodeSimulatorCert {
    static var version: String {
        return "0.1.0"
    }
}
